[project]
name = "optim4ai"
version = "0.1.0"
description = "Optimisation for Artificial Intelligence"
authors = ["Xavier Olive <git@xoolive.org>"]
channels = ["conda-forge", "pytorch"]
platforms = ["win-64", "linux-64", "osx-arm64"]

[tasks]

[dependencies]
python = ">= 3.12"
numpy = ">=2.1.3,<2.2"
scipy = ">=1.14.1,<1.15"
matplotlib = ">=3.9.2,<3.10"
pytorch = ">=2.5.1,<2.6"
pulp = ">=2.8.0,<2.9"
docplex = ">=2.28.240,<2.29"
pip = ">=24.3.1,<24.4"
mypy = ">=1.13.0,<1.14"
ruff = ">=0.7.4,<0.8"

[pypi-dependencies]
gurobipy = "*"
# facile = ">=1.6"
